#!/usr/bin/python3
# Creates a database

import random
import string
import subprocess
import sys

from common import (
    get_db_cursor,
    user,
    service_password,
)

from charmhelpers.core.hookenv import (
    action_fail,
    action_set,
    log,
)


def runsql(sql):
    print("[{}]".format(sql))
    cursor.execute(sql)


def generate_dbname():
    dbname = ''.join([
        random.choice(string.ascii_letters + string.digits)
        for n in xrange(32)
    ])

    return dbname


cursor = get_db_cursor()

log('generating a database name')
database_name = generate_dbname()
log(database_name)

cursor.execute("show databases")
databases = [i[0] for i in cursor.fetchall()]
if database_name in databases:
    log("database exists already")
    action_fail("Database exists already.")
    sys.exit(0)
else:
    log("Creating database")
    runsql("create database `%s` character set utf8" % database_name)

    runsql(
        "grant all on `%s`.* to `%s` identified by '%s'" % (
            database_name,
            user,
            service_password))

    hostname = subprocess.check_output([
        'unit-get',
        'private-address']).strip()
    log("Found hostname {}".format(hostname))
    action_set({
        'database': database_name,
        'user': user,
        'password': service_password,
        'host': hostname
    })
